sudo: required
dist: trusty
language: node_js
node_js:
- '5'
- '6'
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- openssl aes-256-cbc -K $encrypted_ef3fa096c499_key -iv $encrypted_ef3fa096c499_iv
  -in deploy_key.enc -out deploy_key -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- "npm i -g npm@^3"
before_script:
- npm install
script:
- sh script.sh
- npm run lint
- npm test
- npm run build:prod
after_success:
- sh deploy.sh
