sudo: required
dist: trusty
language: node_js
node_js:
  - '6'
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - openssl aes-256-cbc -K $encrypted_ef3fa096c499_key -iv $encrypted_ef3fa096c499_iv
    -in ci/deploy_key.enc -out deploy_key -d
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - sh ci/script.sh
  - ng lint && ng test --watch=false && ng build --aot --prod && yarn sw && mv dist/service-worker.js dist/sw.js
after_success:
  - sh ci/deploy.sh
cache:
  yarn: true
  directories:
    - node_modules
