sudo: required
dist: trusty
language: node_js
node_js:
- '5'
- '6'
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- openssl aes-256-cbc -K $encrypted_ef3fa096c499_key -iv $encrypted_ef3fa096c499_iv
  -in deploy_key.enc -out deploy_key -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- "npm i -g npm@^3"
before_script:
- npm install
- sed -i -- 's/common_1.FORM_DIRECTIVES,//g' node_modules/ng2-charts/components/charts/charts.js
- cp src/api.config.ts.dist src/api.config.ts
script:
- npm run lint
- npm test
- |
  touch ./version.js
  if ([ ! -z "$TRAVIS_TAG" ]) &&
    [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "exports.version = \"$TRAVIS_TAG\";" > ./version.js
  else
    echo "exports.version = \"dev\";" > ./version.js
  fi
- npm run build:prod
after_success:
- |
  if ([ ! -z "$TRAVIS_TAG" ]) &&
    [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "Deploying $TRAVIS_TAG to server"
    chmod 600 deploy_key
    mv deploy_key ~/.ssh/id_rsa
    touch dist/assets/version.json
    echo "{ \"version\": \"$TRAVIS_TAG\" }" > dist/assets/version.json
    tar -czf transfer.tgz dist
    scp -o "StrictHostKeyChecking no" transfer.tgz jenkins@159.203.6.130:/var/www/meditation-plus
    ssh -o "StrictHostKeyChecking no" jenkins@159.203.6.130 'cd /var/www/meditation-plus; rm -rf client; mkdir client; tar -xzf transfer.tgz -C client --strip 1; rm transfer.tgz'
  fi
